# Generated by Django 3.1.8 on 2024-09-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
