# Generated by Django 3.1.8 on 2024-09-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240922_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present',
            name='username',
        ),
        migrations.RemoveField(
            model_name='time',
            name='username',
        ),
    ]
