# Generated by Django 3.1.8 on 2024-09-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_usertime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTime',
        ),
    ]
